apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\joris\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cockatoo-frontend
  name: cockatoo-frontend
spec:
  ports:
    - port: 5173
      targetPort: 80
      protocol: TCP
  selector:
    io.kompose.service: cockatoo-frontend
