apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockatoo-gateway
  labels:
    io.kompose.service: cockatoo-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cockatoo-gateway
  template:
    metadata:
      labels:
        io.kompose.service: cockatoo-gateway
    spec:
      containers:
        - name: cockatoo-gateway
          image: theartcher/cockatoo-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 400m
            requests:
              cpu: 200m
          env:
            - name: BETTERSTACK_SOURCETOKEN
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: BETTERSTACK_SOURCETOKEN
            - name: BETTERSTACK_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: BETTERSTACK_ENDPOINT
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: AUTH0_DOMAIN
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: AUTH0_AUDIENCE
      restartPolicy: Always
